name: Github CI
on: [push, pull_request]

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.2.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: test
        run: |
          npm install
          npm test
        working-directory: ./backend

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: test
        run: |
          npm install
          npm test
        working-directory: ./frontend
